/**
 * Caddy reverse proxy management on Hetzner servers.
 *
 * Each Hetzner server runs Caddy as a gateway proxy:
 *   https://server-ip/gw/<instance-id>/* → container-ip:18789
 *
 * Caddy config is managed via its admin API (localhost:2019).
 * Routes are added/removed when instances are created/deleted.
 */

import { createLogger } from '@ampere/shared/logger';
import { GATEWAY_PORT } from '@ampere/shared/constants/infra';
import { sshExec } from './incus.js';
import { env } from '@ampere/shared/env';
import { toErrorMessage } from '@ampere/shared/errors';
const log = createLogger('orchestrator');

/**
 * Per-server mutex to prevent concurrent Caddy config writes.
 * Without this, parallel provisions on the same server race:
 * both read the instance list, both write the Caddyfile, and
 * the second write drops the route added by the first.
 */
const serverLocks = new Map<string, Promise<void>>();

async function withServerLock<T>(serverIp: string, fn: () => Promise<T>): Promise<T> {
  // Chain onto any existing lock for this server
  const prev = serverLocks.get(serverIp) || Promise.resolve();
  let resolve: () => void;
  const next = new Promise<void>((r) => {
    resolve = r;
  });
  serverLocks.set(serverIp, next);

  await prev; // wait for previous write to finish
  try {
    return await fn();
  } finally {
    resolve!();
    // Clean up if we're the last in the chain
    if (serverLocks.get(serverIp) === next) {
      serverLocks.delete(serverIp);
    }
  }
}

const CADDY_PROXY_PORT = env.CADDY_PROXY_PORT;
const CADDY_AUTH_SECRET = env.CADDY_AUTH_SECRET;

/**
 * Generate the full Caddyfile content for a server.
 * Called with the list of all active instances on that server.
 */
function generateCaddyfile(
  instances: Array<{ instanceId: string; containerIp: string; containerName?: string; hasBrowser?: boolean }>,
): string {
  const routes = instances
    .map(({ instanceId, containerIp, containerName, hasBrowser }) => {
      const name = containerName || `oc-${instanceId.split('-')[0]}`;
      let route = `
    handle_path /gw/${instanceId}/* {
      reverse_proxy unix//run/ampere/${name}.sock ${containerIp}:${GATEWAY_PORT} {
        lb_policy first
        lb_try_duration 2s
      }
    }`;
      if (hasBrowser) {
        route += `

    handle_path /browser/${instanceId}/* {
      reverse_proxy unix//run/ampere/${name}-browser.sock
    }`;
      }
      return route;
    })
    .join('\n');

  // CADDY_AUTH_SECRET must be set in production. Adds header validation for /gw/* routes.
  const authBlock = CADDY_AUTH_SECRET
    ? `
    # Auth: require X-Ampere-Secret header for /gw/* routes
    @gw_no_auth {
      path /gw/*
      not header X-Ampere-Secret ${CADDY_AUTH_SECRET}
    }
    respond @gw_no_auth "Forbidden" 403
`
    : '';

  return `# Auto-generated by Ampere orchestrator — do not edit manually
:${CADDY_PROXY_PORT} {
  route {
    # Health check (handled first)
    respond /health "ok" 200
${authBlock}
${routes}

    # Default: 404
    respond "Not found" 404
  }
}
`;
}

/**
 * Read existing Caddyfile prefix (everything before the orchestrator marker).
 * Preserves non-orchestrator blocks (e.g. :3080 for frontend routing).
 */
async function readCaddyPrefix(serverIp: string): Promise<string> {
  const MARKER = '# Auto-generated by Ampere orchestrator';
  try {
    const existing = await sshExec(serverIp, 'cat /etc/caddy/Caddyfile 2>/dev/null || echo ""', 10_000);
    if (!existing.trim()) return '';
    const markerIdx = existing.indexOf(MARKER);
    if (markerIdx === -1) {
      // No marker found — check for legacy "# Auto-generated" marker (old caddy.ts format)
      const legacyIdx = existing.indexOf('# Auto-generated');
      if (legacyIdx !== -1) {
        // Old-format Caddyfile — discard entirely, let generateCaddyfile rebuild it
        log.info('caddy.legacy_caddyfile_replaced', { serverIp });
        return '';
      }
      // Bare stub Caddyfile (from server setup) with no real routes — discard it
      // to avoid duplicate :8443 blocks that fail Caddy validation
      if (!existing.includes('handle_path') && !existing.includes('reverse_proxy')) {
        log.info('caddy.bare_stub_replaced', { serverIp });
        return '';
      }
      // Truly user-managed file with custom routes, preserve it all
      return existing.trim() + '\n\n';
    }
    if (markerIdx === 0) {
      // Marker is at the very start — no user prefix to preserve
      return '';
    }
    const prefix = existing.substring(0, markerIdx).trim();
    return prefix ? prefix + '\n\n' : '';
  } catch (err: unknown) {
    log.error('caddy.read_prefix_failed', { serverIp, error: toErrorMessage(err) });
    throw new Error(`Failed to read Caddyfile prefix from ${serverIp}: ${toErrorMessage(err)}`, { cause: err });
  }
}

/**
 * Write Caddyfile and reload Caddy on a Hetzner server.
 * Preserves any non-orchestrator blocks before the auto-generated marker.
 */
async function writeCaddyConfig(
  serverIp: string,
  instances: Array<{ instanceId: string; containerIp: string; containerName?: string; hasBrowser?: boolean }>,
): Promise<void> {
  let prefix: string;
  try {
    prefix = await readCaddyPrefix(serverIp);
  } catch (err: unknown) {
    // Abort write to avoid silently wiping user-managed Caddy blocks (e.g. :3080 frontend)
    log.error('caddy.write_aborted', { serverIp, reason: 'prefix read failed', error: toErrorMessage(err) });
    return;
  }
  const caddyfile = prefix + generateCaddyfile(instances);
  // Randomized heredoc delimiter to prevent injection
  const delimiter = `CADDYEOF_${Math.random().toString(36).slice(2, 10)}`;

  // Write to temp file first, validate, then move into place
  await sshExec(serverIp, `cat > /etc/caddy/Caddyfile.new << '${delimiter}'\n${caddyfile}\n${delimiter}`);

  // Validate with Caddy's parser before applying
  try {
    await sshExec(serverIp, 'caddy validate --config /etc/caddy/Caddyfile.new 2>&1');
  } catch (err: unknown) {
    log.error('caddy.validation_failed', { serverIp, error: toErrorMessage(err) });
    await sshExec(serverIp, 'rm -f /etc/caddy/Caddyfile.new').catch(() => {
      /* best-effort: temp file cleanup is non-critical */
    });
    throw new Error(`Caddyfile validation failed on ${serverIp}: ${toErrorMessage(err)}`, { cause: err });
  }

  // Validated — move into place and reload
  await sshExec(serverIp, 'mv /etc/caddy/Caddyfile.new /etc/caddy/Caddyfile');
  await sshExec(serverIp, 'systemctl reload caddy 2>/dev/null || systemctl restart caddy');
  log.info('caddy.config_updated', { serverIp, routeCount: instances.length });
}

/**
 * Add a route for a new instance. Reads current instances from orchestrator DB.
 * Uses per-server lock to prevent concurrent writes from dropping routes.
 *
 * NOTE: allInstances is accepted for backward compat but re-queried inside the
 * lock via refreshFn (if provided) to avoid stale reads from before lock acquisition.
 */
export async function addRoute(
  serverIp: string,
  instanceId: string,
  containerIp: string,
  allInstances: Array<{ instanceId: string; containerIp: string; containerName?: string; hasBrowser?: boolean }>,
  opts?: {
    hasBrowser?: boolean;
    containerName?: string;
    refreshFn?: () => Array<{ instanceId: string; containerIp: string; containerName?: string; hasBrowser?: boolean }>;
  },
): Promise<void> {
  await withServerLock(serverIp, async () => {
    // Re-query inside the lock to get fresh data if refreshFn provided
    const freshInstances = opts?.refreshFn ? opts.refreshFn() : allInstances;
    const existing = freshInstances.find((i) => i.instanceId === instanceId);
    const containerName = opts?.containerName || existing?.containerName || `oc-${instanceId.split('-')[0]}`;
    log.info('caddy.addroute_server', {
      serverIp: serverIp,
      instanceId: instanceId,
      containerName,
      hasBrowser: opts?.hasBrowser || false,
    });
    const instances = [
      ...freshInstances.filter((i) => i.instanceId !== instanceId),
      { instanceId, containerIp, containerName, hasBrowser: opts?.hasBrowser },
    ];
    await writeCaddyConfig(serverIp, instances);
  });
}

/**
 * Remove a route when an instance is deleted.
 * Uses per-server lock to prevent concurrent writes from dropping routes.
 */
export async function removeRoute(
  serverIp: string,
  instanceId: string,
  allInstances: Array<{ instanceId: string; containerIp: string; containerName?: string; hasBrowser?: boolean }>,
): Promise<void> {
  await withServerLock(serverIp, async () => {
    log.info('caddy.removeroute_server', { serverIp: serverIp, instanceId: instanceId });
    const instances = allInstances.filter((i) => i.instanceId !== instanceId);
    await writeCaddyConfig(serverIp, instances);
  });
}

/**
 * Get the proxy URL for an instance on a given server.
 * This is what the portal uses to connect.
 */
export function getProxyUrl(serverIp: string, instanceId: string): string {
  return `http://${serverIp}:${CADDY_PROXY_PORT}/gw/${instanceId}/`;
}

/**
 * Get the WebSocket URL for an instance.
 */
export function getWsUrl(serverIp: string, instanceId: string): string {
  return `ws://${serverIp}:${CADDY_PROXY_PORT}/gw/${instanceId}/`;
}

/**
 * Check if Caddy is running and healthy on a server.
 */
async function isHealthy(serverIp: string): Promise<boolean> {
  try {
    await sshExec(serverIp, `curl -sf http://127.0.0.1:${CADDY_PROXY_PORT}/health`, 5000);
    return true;
  } catch (err: unknown) {
    log.debug('caddy.is_healthy_check_failed', { error: toErrorMessage(err) });
    return false;
  }
}

export { CADDY_PROXY_PORT, GATEWAY_PORT, CADDY_AUTH_SECRET };
